'use client'

import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import { authClient } from '@/lib/auth-client'

export function AuthForm({ mode }: { mode: 'login' | 'signup' | 'forgot' }) {
  const router = useRouter(); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(''); setSuccess(''); const data = new FormData(event.currentTarget); const email = String(data.get('email') || '').trim(); const password = String(data.get('password') || '');
    try { if (mode === 'forgot') { const result = await authClient.requestPasswordReset({ email, redirectTo: `${window.location.origin}/reset-password` }); if (result.error) throw new Error('No se pudo procesar la solicitud.'); setSuccess('Si el correo existe, recibirás instrucciones para recuperar tu contraseña.'); }
      else if (mode === 'login') { const result = await authClient.signIn.email({ email, password }); if (result.error) throw new Error('Correo o contraseña incorrectos.'); router.push('/'); router.refresh() }
      else { const name = `${data.get('name') || ''} ${data.get('lastName') || ''}`.trim(); if (password !== data.get('confirmPassword')) throw new Error('Las contraseñas no coinciden.'); const result = await authClient.signUp.email({ email, password, name }); if (result.error) throw new Error('No se pudo crear la cuenta.'); router.push('/'); router.refresh() }
    } catch (err) { setError(err instanceof Error ? err.message : 'No se pudo completar la operación.') } finally { setLoading(false) }
  }
  const title = mode === 'login' ? 'Bienvenido de nuevo.' : mode === 'signup' ? 'Crea tu cuenta.' : 'Recupera el acceso.'
  return <main className="auth-shell"><div className="auth-orbit" aria-hidden="true"/><div className="auth-panel"><div className="auth-brand"><span>◆</span> NEXUS <b>/ EMERGENCY</b></div><div className="auth-kicker">CENTRO DE CONTROL · ACCESO SEGURO</div><h1>{title}</h1><p className="auth-subtitle">{mode === 'login' ? 'Ingresa para continuar al centro de operaciones.' : mode === 'signup' ? 'Registra tus datos para formar parte de la red de respuesta.' : 'Te enviaremos un enlace seguro a tu correo.'}</p><form onSubmit={submit} className="auth-form">{mode === 'signup' && <div className="auth-grid"><label>Nombre<input name="name" required autoComplete="given-name" /></label><label>Apellido<input name="lastName" required autoComplete="family-name" /></label><label className="wide">Dirección<input name="address" autoComplete="street-address" /></label><label>DNI<input name="dni" inputMode="numeric" /></label><label>Celular<input name="phone" inputMode="tel" autoComplete="tel" /></label></div>}<label>Correo electrónico<input name="email" type="email" required autoComplete="email" /></label>{mode !== 'forgot' && <><label>Contraseña<input name="password" type="password" required minLength={8} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} /></label>{mode === 'signup' && <label>Confirmar contraseña<input name="confirmPassword" type="password" required minLength={8} autoComplete="new-password" /></label>}</>}{error && <p className="auth-message error" role="alert">{error}</p>}{success && <p className="auth-message success">{success}</p>}<button className="auth-submit" disabled={loading}>{loading ? 'Procesando…' : mode === 'login' ? 'Ingresar al sistema' : mode === 'signup' ? 'Crear cuenta' : 'Enviar enlace'}</button></form><div className="auth-links">{mode === 'login' && <><a href="/forgot-password">¿Olvidaste tu contraseña?</a><span>¿No tienes una cuenta? <a href="/sign-up">Crear cuenta</a></span></>}{mode === 'signup' && <span>¿Ya tienes una cuenta? <a href="/login">Iniciar sesión</a></span>}{mode === 'forgot' && <span>¿Recordaste tu contraseña? <a href="/login">Volver al acceso</a></span>}</div><small className="auth-footer">Protegido por autenticación cifrada · NEXUS 2026</small></div></main>
}
